# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Deploy to GitHub Pages

# Déclencheur : ce workflow s'exécute à chaque push sur la branche "main"
on:
  # NOUVEAU : Permet de déclencher manuellement ce workflow depuis l'onglet Actions
  workflow_dispatch:

  # Déclenche aussi automatiquement à chaque push sur la branche "main"
  push:
    branches:
      - main  # ou 'master' selon le nom de votre branche principale

# Permissions : accorde les permissions nécessaires pour que l'action puisse écrire sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Jobs : une liste des tâches à exécuter
jobs:
  # Tâche de déploiement
  deploy:
    # Environnement requis pour le déploiement sur GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Type de machine virtuelle à utiliser
    runs-on: ubuntu-latest
    
    # Étapes de la tâche
    steps:
      # 1. Récupère le code de votre dépôt
      - name: Checkout
        uses: actions/checkout@v4 # MISE À JOUR

      # 2. Remplace les placeholders par les vrais secrets
      - name: Replace Firebase config placeholders
        run: |
          # Utilise la commande 'sed' pour trouver et remplacer les placeholders dans le fichier index.html
          sed -i 's|PLACEHOLDER_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g' index.html
          sed -i 's|PLACEHOLDER_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' index.html
          sed -i 's|PLACEHOLDER_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g' index.html
          sed -i 's|PLACEHOLDER_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' index.html
          sed -i 's|PLACEHOLDER_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' index.html
          sed -i 's|PLACEHOLDER_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g' index.html

      # 3. Prépare les fichiers du site pour le déploiement
      - name: Setup Pages
        uses: actions/configure-pages@v5 # MISE À JOUR

      # 4. Met en ligne les fichiers du site en tant qu'artefact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # MISE À JOUR
        with:
          # Met en ligne le contenu du dossier racine
          path: '.'

      # 5. Déploie l'artefact sur GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # MISE À JOUR
